<div class="content-wrapper">
                  <h1 class="page-title">HeatMap</h1>
                  <div class="row">
                     <div class="col-lg-8 grid-margin d-flex align-items-stretch">
                        <div class="card w-100">
                           <div class="card-body">
                              <div class="container">
                                 <div class="mapcontainer mapeal-example-2">
                                    <div class="map"><span>Alternative content for the map</span></div>
                                    <div class="myLegend"><span>Alternative content for the legend</span></div>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                     <div class="col-lg-4 col-md-12 col-sm-12 grid-margin drag-item">
                        <div class="card">
                           <div class="card-body">
                              <h2 class="card-title">Sales by Top Locations (YTD)</h2>
                              <div class="row">
                                 <div class="col-sm-12 col-xs-12 table-responsive">
                                    <table class="table table-striped">
                                       <tbody>
                                          <tr>
                                             <td>
                                                <div class="flag">
                                                   <i class="flag-icon flag-icon-us"></i>
                                                </div>
                                             </td>
                                             <td>Los Angeles, CA (Store #311)</td>
                                            
                                             <td class="text-right">
                                                $9,132,131.23
                                             </td>
                                          </tr>
                                          <tr>
                                             <td>
                                                <div class="flag">
                                                   <i class="flag-icon flag-icon-us"></i>
                                                </div>
                                             </td>
                                             <td>Sacramento, CA (Store #11)</td>
                                            
                                             <td class="text-right">
                                                $8,245,311.59
                                             </td>
                                          </tr>
                                          <tr>
                                             <td>
                                                <div class="flag">
                                                   <i class="flag-icon flag-icon-us"></i>
                                                </div>
                                             </td>
                                             <td>Reno, NV (Store #21)</td>
                                            
                                             <td class="text-right">
                                                $8,078,421.90
                                             </td>
                                          </tr>
                                          <tr>
                                             <td>
                                                <div class="flag">
                                                   <i class="flag-icon flag-icon-us"></i>
                                                </div>
                                             </td>
                                             <td>Downey, CA (#25)</td>
                                            
                                             <td class="text-right">
                                                $5,922,189.35
                                             </td>
                                          </tr>
                                          <tr>
                                             <td>
                                                <div class="flag">
                                                   <i class="flag-icon flag-icon-us"></i>
                                                </div>
                                             </td>
                                             <td>City of Industry, CA (#34)</td>
                                            
                                             <td class="text-right">
                                                $4,754,678.65
                                             </td>
                                          </tr>
                                          <tr>
                                             <td>
                                                <div class="flag">
                                                   <i class="flag-icon flag-icon-us"></i>
                                                </div>
                                             </td>
                                             <td>Bellflower, CA (Store #30)</td>
                                            
                                             <td class="text-right">
                                                $4,548,562.74
                                             </td>
                                          </tr>
                                          <tr>
                                             <td>
                                                <div class="flag">
                                                   <i class="flag-icon flag-icon-us"></i>
                                                </div>
                                             </td>
                                             <td>Alhambra, CA (Store #47)</td>
                                            
                                             <td class="text-right">
                                                $2,868,265.32
                                             </td>
                                          </tr>
                                          <tr>
                                             <td>
                                                <div class="flag">
                                                   <i class="flag-icon flag-icon-us"></i>
                                                </div>
                                             </td>
                                             <td>Las Vegas, NV (Store #89)</td>
                                            
                                             <td class="text-right">
                                                $1,198,586.12
                                             </td>
                                          </tr>
                                          <tr>
                                             <td>
                                                <div class="flag">
                                                   <i class="flag-icon flag-icon-us"></i>
                                                </div>
                                             </td>
                                             <td>Chicago, IL (Store #159)</td>
                                            
                                             <td class="text-right">
                                                $1,168,876.09
                                             </td>
                                          </tr>
                                          <tr>
                                             <td>
                                                <div class="flag">
                                                   <i class="flag-icon flag-icon-us"></i>
                                                </div>
                                             </td>
                                             <td>New York City, NY (Store #56)</td>
                                            
                                             <td class="text-right">
                                                $1,008,586.12
                                             </td>
                                          </tr>
                                          <tr>
                                             <td>
                                                <div class="flag">
                                                   <i class="flag-icon flag-icon-us"></i>
                                                </div>
                                             </td>
                                             <td>Seattle, WA (Store #213)</td>
                                            
                                             <td class="text-right">
                                                $987,106.02
                                             </td>
                                          </tr>
                                       </tbody>
                                    </table>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
