        <div class="content-wrapper">
          <h1 class="page-title">Sales Calender</h1>
          <div class="row">
              <div class="col-lg-12">
                  <div class="card">
                      <div class="card-body">
                          <div id="calendar"></div>
                      </div>
                  </div>
              </div>
          </div>
        </div>
