        <nav class="sidebar sidebar-offcanvas" id="sidebar">
          <div class="user-info">
            <div class="profile">
              <img src="http://via.placeholder.com/47x47" alt="">
            </div>
            <div class="details">
              <p class="user-name">Aaron Pelto</p>
              <p class="designation">VTail LLC</p>
            </div>
          </div>
          <ul class="nav">
            <!--main pages start-->
            <li class="nav-item nav-category">
              <span class="nav-link">Administration</span>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/Dashboard">
                <i class="mdi mdi-gauge menu-icon"></i>
                <span class="menu-title">Dashboard</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/Machines">
                <i class="mdi mdi-cube-outline menu-icon"></i>
                <span class="menu-title">Machines</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/Orders">
                <i class="mdi mdi-cart-outline menu-icon"></i>
                <span class="menu-title">Order Product</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/Profile">
                <i class="mdi mdi-buffer menu-icon"></i>
                <span class="menu-title">Account</span>
              </a>
            </li>
            <li class="nav-item nav-category">
              <span class="nav-link">Sales</span>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/Search">
                <i class="mdi mdi-file-document-box menu-icon"></i>
                <span class="menu-title">Search Transactions</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/Calendar">
                <i class="mdi mdi-table-large menu-icon"></i>
                <span class="menu-title">Calendar</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/Heatmap">
                <i class="mdi mdi-map-marker-outline menu-icon"></i>
                <span class="menu-title">HeatMap</span>
              </a>
            </li>
            <!--main pages end-->
          </ul>
        </nav>        