        <div class="content-wrapper">
          <div class="card">
            <div class="card-body">
              <h2 class="card-title">Order Product Refills</h2>
              <div class="row grid-margin">
                <div class="col-12 col-lg-4 ml-lg-auto">
                    
                </div>
              </div>

              <div class="row">
                <div class="col-12">
                  <table id="" class="table table-striped" style="border-spacing: 0px;border-collapse: separate;width:100%;">
                    <thead>
                      <tr>
                          <th>Product</th>
                          <th>SKU</th>
                          <th>Price</th>
                          <th>Minimum Quantity</th>
                          <th>Compatibility</th>
                          <th>Actions</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                          <td>Mix #17</td>
                          <td>VMIX-17</td>
                          <td>$149.50/case</td>
                          <td>2</td>
                          <td>Lumini Series, Web Glow Machine</td>
                          <td>
                            <button class="btn btn-outline-primary">Purchase</button>
                          </td>
                      </tr>
                      <tr>
                          <td>Mix #20</td>
                          <td>VMIX-20</td>
                          <td>$149.50/case</td>
                          <td>2</td>
                          <td>Lumini Series, Web Glow Machine</td>
                          <td>
                            <button class="btn btn-outline-primary">Purchase</button>
                          </td>
                      </tr>
                      <tr>
                          <td>Mix #21</td>
                          <td>VMIX-21</td>
                          <td>$149.50/case</td>
                          <td>2</td>
                          <td>Lumini Series, Web Glow Machine</td>
                          <td>
                            <button class="btn btn-outline-primary">Purchase</button>
                          </td>
                      </tr>
                      <tr>
                          <td>Mix #23</td>
                          <td>VMIX-23</td>
                          <td>$149.50/case</td>
                          <td>2</td>
                          <td>Lumini Series, Web Glow Machine</td>
                          <td>
                            <button class="btn btn-outline-primary">Purchase</button>
                          </td>
                      </tr>
                      <tr>
                          <td>Mix #24</td>
                          <td>VMIX-24</td>
                          <td>$149.50/case</td>
                          <td>2</td>
                          <td>Lumini Series, Web Glow Machine</td>
                          <td>
                            <button class="btn btn-outline-primary">Purchase</button>
                          </td>
                      </tr>
                      <tr>
                          <td>Mix #25</td>
                          <td>VMIX-25</td>
                          <td>$150/case</td>
                          <td>2</td>
                          <td>Lumini Series, Primo</td>
                          <td>
                            <button class="btn btn-outline-primary">Purchase</button>
                          </td>
                      </tr>
                      <tr>
                          <td>Mix #26</td>
                          <td>VMIX-26</td>
                          <td>$150/case</td>
                          <td>2</td>
                          <td>Lumini Series, Primo</td>
                          <td>
                            <button class="btn btn-outline-primary">Purchase</button>
                          </td>
                      </tr>
                      <tr>
                          <td>Mix #202</td>
                          <td>PRIM-202</td>
                          <td>$150/case</td>
                          <td>2</td>
                          <td>Primo, Web Glow Machine</td>
                          <td>
                            <button class="btn btn-outline-primary">Purchase</button>
                          </td>
                      </tr>
                      <tr>
                          <td>Primo Prize Mix</td>
                          <td>PRIMOMIX</td>
                          <td>$149.50/case</td>
                          <td>2</td>
                          <td>Primo</td>
                          <td>
                            <button class="btn btn-outline-primary">Purchase</button>
                          </td>
                      </tr>
                      <tr>
                          <td>Vend Sticks</td>
                          <td>VMIX-23</td>
                          <td>$149.50/300pcs</td>
                          <td>1</td>
                          <td>Web Glow Machine</td>
                          <td>
                            <button class="btn btn-outline-primary">Purchase</button>
                          </td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
