               <div class="content-wrapper grid-stack">
                  <h1 class="page-title">Machine Overview</h1>
                  <div class="row bg-vpurple mb-4">
                     <div class="col-sm-3">
                        <div class="card-body row">
                           <label class="col-sm-12 col-md-3 col-form-label">Location</label>
                           <select id="example1" class="form-control col-sm-12 col-md-9">
                              <option value="1">Los Angeles, CA (Store #311)</option>
                              <option value="2">Sacramento, CA (Store #11)</option>
                              <option value="3">Reno, NV (Store #21)</option>
                              <option value="4">Downey, CA (#25)</option>
                              <option value="5">City of Industry, CA (#34)</option>
                              <option value="6">Bellflower, CA (Store #30)</option>
                              <option value="7">Alhambra, CA (Store #47)</option>
                              <option value="8">Las Vegas, NV (Store #89)</option>
                           </select>
                        </div>
                     </div>
                     <div class="col-sm-3">
                        <div class="card-body row">
                           <label class="col-sm-12 col-md-3 col-form-label">Sales Data</label>
                           <select id="example1" class="form-control col-sm-12 col-md-9">
                              <option value="1">Last 24 Hours</option>
                              <option value="2">By Week</option>
                              <option value="3">By Month</option>
                              <option value="4">Year To Date</option>
                           </select>
                        </div>
                     </div>
                     <div class="col-sm-2">
                        <div class="card-body row">
                           <label class="col-sm-12 col-md-4 col-form-label">Status</label>
                           <select id="example1" class="form-control col-sm-12 col-md-6">
                              <option value="1">All</option>
                              <option value="2">Online</option>
                              <option value="4">Offline</option>
                              <option value="3">Cashbox Full</option>
                           </select>
                        </div>
                     </div>
                  </div>
                  <div class="row">
                     <!-- Sale Data -->
                     <div class="col-xl-3 col-lg-6 col-md-6 col-sm-12 grid-margin drag-item align-items-stretch">
                        <div class="col-sm-12 h-100">
                           <div class="float-none">
                              <div class="col-12 badge  badge-success p-3">Online</div>
                           </div>
                           <div class="card w-100 h-100">
                              <div class="card-body">
                                 <div class="clearfix">
                                    <div class="float-none text-center">
                                       <h1 class="display-3">Lumini X</h1>
                                    </div>
                                    <div class="float-left">
                                       <i class="fa highlight-icon fa fa-usd text-success fa-2x" aria-hidden="true"></i>
                                    </div>
                                    <div class="float-right">
                                       <p class="card-text">Revenue</p>
                                       <div class="fluid-container d-flex align-items-center">
                                          <i class="fa fa-angle-double-up text-success mr-2 fa-2x" aria-hidden="true"></i>
                                          <h4 class="card-title font-weight-normal mb-0">$11,231</h4>
                                       </div>
                                    </div>
                                    <div class="float-none">
                                       <img src="../images/lumini_preview.png" class="mw-100">
                                    </div>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                     <div class="col-xl-3 col-lg-6 col-md-6 col-sm-12 grid-margin drag-item align-items-stretch">
                        <div class="col-sm-12 h-100">
                           <div class="float-none">
                              <div class="col-12 badge  badge-warning p-3">Cashbox Full</div>
                           </div>
                           <div class="card w-100 h-100">
                              <div class="card-body">
                                 <div class="clearfix">
                                    <div class="float-none text-center">
                                       <h1 class="display-3">Primo</h1>
                                    </div>
                                    <div class="float-left">
                                       <i class="fa highlight-icon fa fa-exclamation-triangle text-warning fa-2x" aria-hidden="true"></i>
                                    </div>
                                    <div class="float-right">
                                       <p class="card-text">Revenue</p>
                                       <div class="fluid-container d-flex align-items-center">
                                          <i class="fa fa-angle-double-up text-success mr-2 fa-2x" aria-hidden="true"></i>
                                          <h4 class="card-title font-weight-normal mb-0">$12,879</h4>
                                       </div>
                                    </div>
                                    <div class="float-none">
                                       <img src="../images/primo_preview.png" class="mw-100">
                                    </div>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                     <div class="col-xl-3 col-lg-6 col-md-6 col-sm-12 grid-margin drag-item align-items-stretch">
                        <div class="col-sm-12 h-100">
                           <div class="float-none">
                              <div class="col-12 badge  badge-success p-3">Online</div>
                           </div>
                           <div class="card w-100 h-100">
                              <div class="card-body">
                                 <div class="clearfix">
                                    <div class="float-none text-center">
                                       <h1 class="display-3">Web Glow Machine</h1>
                                    </div>
                                    <div class="float-left">
                                       <i class="fa highlight-icon fa fa-usd text-success fa-2x" aria-hidden="true"></i>
                                    </div>
                                    <div class="float-right">
                                       <p class="card-text">Revenue</p>
                                       <div class="fluid-container d-flex align-items-center">
                                          <i class="fa fa-angle-double-up text-success mr-2 fa-2x" aria-hidden="true"></i>
                                          <h4 class="card-title font-weight-normal mb-0">$23,456</h4>
                                       </div>
                                    </div>
                                    <div class="float-none">
                                       <img src="../images/wgm_preview.png" class="mw-100">
                                    </div>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                     <div class="col-xl-3 col-lg-6 col-md-6 col-sm-12 grid-margin drag-item align-items-stretch">
                        <div class="col-sm-12 h-100">
                           <div class="float-none">
                              <div class="col-12 badge  badge-danger p-3">Offline</div>
                           </div>
                           <div class="card w-100 h-100">
                              <div class="card-body">
                                 <div class="clearfix">
                                    <div class="float-none text-center">
                                       <h1 class="display-3">Lumini X</h1>
                                    </div>
                                    <div class="float-left">
                                       <i class="fa highlight-icon fa fa-exclamation-triangle text-danger fa-2x" aria-hidden="true"></i>
                                    </div>
                                    <div class="float-right">
                                       <p class="card-text">Revenue</p>
                                       <div class="fluid-container d-flex align-items-center">
                                          <i class="fa fa-angle-double-up text-success mr-2 fa-2x" aria-hidden="true"></i>
                                          <h4 class="card-title font-weight-normal mb-0">$17,479</h4>
                                       </div>
                                    </div>
                                    <div class="float-none">
                                       <img src="../images/lumini_preview.png" class="mw-100">
                                    </div>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                     <div class="col-xl-3 col-lg-6 col-md-6 col-sm-12 grid-margin drag-item align-items-stretch">
                        <div class="col-sm-12 h-100">
                           <div class="float-none">
                              <div class="col-12 badge  badge-success p-3">Online</div>
                           </div>
                           <div class="card w-100 h-100">
                              <div class="card-body">
                                 <div class="clearfix">
                                    <div class="float-none text-center">
                                       <h1 class="display-3">Lumini X</h1>
                                    </div>
                                    <div class="float-left">
                                       <i class="fa highlight-icon fa fa-usd text-success fa-2x" aria-hidden="true"></i>
                                    </div>
                                    <div class="float-right">
                                       <p class="card-text">Revenue</p>
                                       <div class="fluid-container d-flex align-items-center">
                                          <i class="fa fa-angle-double-up text-success mr-2 fa-2x" aria-hidden="true"></i>
                                          <h4 class="card-title font-weight-normal mb-0">$18,581</h4>
                                       </div>
                                    </div>
                                    <div class="float-none">
                                       <img src="../images/lumini_preview.png" class="mw-100">
                                    </div>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                     <div class="col-xl-3 col-lg-6 col-md-6 col-sm-12 grid-margin drag-item align-items-stretch">
                        <div class="col-sm-12 h-100">
                           <div class="float-none">
                              <div class="col-12 badge  badge-success p-3">Online</div>
                           </div>
                           <div class="card w-100 h-100">
                              <div class="card-body">
                                 <div class="clearfix">
                                    <div class="float-none text-center">
                                       <h1 class="display-3">Primo</h1>
                                    </div>
                                    <div class="float-left">
                                       <i class="fa highlight-icon fa fa-usd text-success fa-2x" aria-hidden="true"></i>
                                    </div>
                                    <div class="float-right">
                                       <p class="card-text">Revenue</p>
                                       <div class="fluid-container d-flex align-items-center">
                                          <i class="fa fa-angle-double-up text-success mr-2 fa-2x" aria-hidden="true"></i>
                                          <h4 class="card-title font-weight-normal mb-0">$9,874</h4>
                                       </div>
                                    </div>
                                    <div class="float-none">
                                       <img src="../images/primo_preview.png" class="mw-100">
                                    </div>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                     <div class="col-xl-3 col-lg-6 col-md-6 col-sm-12 grid-margin drag-item align-items-stretch">
                        <div class="col-sm-12 h-100">
                           <div class="float-none">
                              <div class="col-12 badge  badge-danger p-3">Offline</div>
                           </div>
                           <div class="card w-100 h-100">
                              <div class="card-body">
                                 <div class="clearfix">
                                    <div class="float-none text-center">
                                       <h1 class="display-3">Web Glow Machine</h1>
                                    </div>
                                    <div class="float-left">
                                       <i class="fa highlight-icon fa fa-exclamation-triangle text-danger fa-2x" aria-hidden="true"></i>
                                    </div>
                                    <div class="float-right">
                                       <p class="card-text">Revenue</p>
                                       <div class="fluid-container d-flex align-items-center">
                                          <i class="fa fa-angle-double-up text-success mr-2 fa-2x" aria-hidden="true"></i>
                                          <h4 class="card-title font-weight-normal mb-0">$23,456</h4>
                                       </div>
                                    </div>
                                    <div class="float-none">
                                       <img src="../images/wgm_preview.png" class="mw-100">
                                    </div>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                     <div class="col-xl-3 col-lg-6 col-md-6 col-sm-12 grid-margin drag-item align-items-stretch">
                        <div class="col-sm-12 h-100">
                           <div class="float-none">
                              <div class="col-12 badge  badge-success p-3">Online</div>
                           </div>
                           <div class="card w-100 h-100">
                              <div class="card-body">
                                 <div class="clearfix">
                                    <div class="float-none text-center">
                                       <h1 class="display-3">Lumini X</h1>
                                    </div>
                                    <div class="float-left">
                                       <i class="fa highlight-icon fa fa-usd text-success fa-2x" aria-hidden="true"></i>
                                    </div>
                                    <div class="float-right">
                                       <p class="card-text">Revenue</p>
                                       <div class="fluid-container d-flex align-items-center">
                                          <i class="fa fa-angle-double-up text-success mr-2 fa-2x" aria-hidden="true"></i>
                                          <h4 class="card-title font-weight-normal mb-0">$17,479</h4>
                                       </div>
                                    </div>
                                    <div class="float-none">
                                       <img src="../images/lumini_preview.png" class="mw-100">
                                    </div>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                     <div class="col-xl-3 col-lg-6 col-md-6 col-sm-12 grid-margin drag-item align-items-stretch">
                        <div class="col-sm-12 h-100">
                           <div class="float-none">
                              <div class="col-12 badge  badge-success p-3">Online</div>
                           </div>
                           <div class="card w-100 h-100">
                              <div class="card-body">
                                 <div class="clearfix">
                                    <div class="float-none text-center">
                                       <h1 class="display-3">Web Glow Machine</h1>
                                    </div>
                                    <div class="float-left">
                                       <i class="fa highlight-icon fa fa-usd text-success fa-2x" aria-hidden="true"></i>
                                    </div>
                                    <div class="float-right">
                                       <p class="card-text">Revenue</p>
                                       <div class="fluid-container d-flex align-items-center">
                                          <i class="fa fa-angle-double-up text-success mr-2 fa-2x" aria-hidden="true"></i>
                                          <h4 class="card-title font-weight-normal mb-0">$23,456</h4>
                                       </div>
                                    </div>
                                    <div class="float-none">
                                       <img src="../images/wgm_preview.png" class="mw-100">
                                    </div>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                     <div class="col-xl-3 col-lg-6 col-md-6 col-sm-12 grid-margin drag-item align-items-stretch">
                        <div class="col-sm-12 h-100">
                           <div class="float-none">
                              <div class="col-12 badge  badge-danger p-3">Offline</div>
                           </div>
                           <div class="card w-100 h-100">
                              <div class="card-body">
                                 <div class="clearfix">
                                    <div class="float-none text-center">
                                       <h1 class="display-3">Lumini X</h1>
                                    </div>
                                    <div class="float-left">
                                       <i class="fa highlight-icon fa fa-exclamation-triangle text-danger fa-2x" aria-hidden="true"></i>
                                    </div>
                                    <div class="float-right">
                                       <p class="card-text">Revenue</p>
                                       <div class="fluid-container d-flex align-items-center">
                                          <i class="fa fa-angle-double-up text-success mr-2 fa-2x" aria-hidden="true"></i>
                                          <h4 class="card-title font-weight-normal mb-0">$17,479</h4>
                                       </div>
                                    </div>
                                    <div class="float-none">
                                       <img src="../images/lumini_preview.png" class="mw-100">
                                    </div>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                     <div class="col-xl-3 col-lg-6 col-md-6 col-sm-12 grid-margin drag-item align-items-stretch">
                        <div class="col-sm-12 h-100">
                           <div class="float-none">
                              <div class="col-12 badge  badge-success p-3">Online</div>
                           </div>
                           <div class="card w-100 h-100">
                              <div class="card-body">
                                 <div class="clearfix">
                                    <div class="float-none text-center">
                                       <h1 class="display-3">Lumini X</h1>
                                    </div>
                                    <div class="float-left">
                                       <i class="fa highlight-icon fa fa-usd text-success fa-2x" aria-hidden="true"></i>
                                    </div>
                                    <div class="float-right">
                                       <p class="card-text">Revenue</p>
                                       <div class="fluid-container d-flex align-items-center">
                                          <i class="fa fa-angle-double-up text-success mr-2 fa-2x" aria-hidden="true"></i>
                                          <h4 class="card-title font-weight-normal mb-0">$18,581</h4>
                                       </div>
                                    </div>
                                    <div class="float-none">
                                       <img src="../images/lumini_preview.png" class="mw-100">
                                    </div>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                     <div class="col-xl-3 col-lg-6 col-md-6 col-sm-12 grid-margin drag-item align-items-stretch">
                        <div class="col-sm-12 h-100">
                           <div class="float-none">
                              <div class="col-12 badge  badge-success p-3">Online</div>
                           </div>
                           <div class="card w-100 h-100">
                              <div class="card-body">
                                 <div class="clearfix">
                                    <div class="float-none text-center">
                                       <h1 class="display-3">Primo</h1>
                                    </div>
                                    <div class="float-left">
                                       <i class="fa highlight-icon fa fa-usd text-success fa-2x" aria-hidden="true"></i>
                                    </div>
                                    <div class="float-right">
                                       <p class="card-text">Revenue</p>
                                       <div class="fluid-container d-flex align-items-center">
                                          <i class="fa fa-angle-double-up text-success mr-2 fa-2x" aria-hidden="true"></i>
                                          <h4 class="card-title font-weight-normal mb-0">$9,874</h4>
                                       </div>
                                    </div>
                                    <div class="float-none">
                                       <img src="../images/primo_preview.png" class="mw-100">
                                    </div>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>

               </div>
