      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <title>VTail Admin - Machine Overview</title>
      <!-- plugins:css -->
      <link rel="stylesheet" href="/node_modules/mdi/css/materialdesignicons.min.css">
      <link rel="stylesheet" href="/node_modules/perfect-scrollbar/dist/css/perfect-scrollbar.min.css">
      <!-- endinject -->
      <!-- plugin css for this page -->
      <link rel="stylesheet" href="/node_modules/flag-icon-css/css/flag-icon.min.css" />
      <link rel="stylesheet" href="/node_modules/font-awesome/css/font-awesome.min.css" />
      <link rel="stylesheet" href="/node_modules/icheck/skins/all.css" />
      <!-- End plugin css for this page -->
      <!-- inject:css -->
      <link rel="stylesheet" href="/css/style.css">
      <!-- endinject -->
      <link rel="shortcut icon" href="/images/favicon.png" />
