        <div class="content-wrapper">

          <div class="row">
            <div class="col-lg-6 col-12 mb-4">
              <div class="card">
                <div class="card-body">
                  <h2 class="card-title">Today's Machine Sales</h2>
                  <div id="morris-area-example"></div>
                </div>
              </div>
              <div class="card w-100">
                <div class="card-body">
                  <h2 class="card-title">Sales By Machine</h2>
                  <ul class="ct-legend mt-5"></ul>
                  <div class="row mx-1 mt-5 d-none d-sm-flex">
                    <div class="col-12">
                    </div>
                    <div class="col-12 col-sm-4 revenue-details text-center text-sm-left">
                      <p class="head text-muted">Lumini X</p>
                      <p class="progess mb-0">$1,621.74</p>
                    </div>
                    <div class="col-12 col-sm-4 d-flex justifiy-content-center flex-column text-center revenue-details">
                      <p class="head text-muted">Primo</p>
                      <p class="progess mb-0">$362.74</p>
                    </div>
                    <div class="col-12 col-sm-4 text-center text-sm-right revenue-details">
                      <p class="head text-muted">Web Glow Machine</p>
                      <p class="progess mb-0">$3,362.74</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-lg-6 col-12 mb-4">
              <div class="card w-100">
                <div class="card-body">
                  <h2 class="card-title">Machine Overview</h2>
                  <ul class="ct-legend mt-5"></ul>
                  <div class="row mx-1 mt-5 d-none d-sm-flex">
                    <div class="col-12">
                      <table class="table mb-0 text-center">
                        <tbody>
                          <tr>
                            <td>Lumini X <i class="fa fa-edit"></i></td>
                            <td>Primo <i class="fa fa-edit"></i></td>
                            <td>Web Glow Machine <i class="fa fa-edit"></i></td>
                          </tr>
                          <tr>
                            <td><img src="images/lumini_preview.png" /></td>
                            <td><img src="images/primo_preview.png" /></td>
                            <td><img src="images/wgm_preview.png" /></td>
                          </tr>
                          <tr>
                            <td><div class="col-12 badge badge-pill  badge-success">Online</div></td>
                            <td><div class="col-12 badge badge-pill  badge-warning">Cashbox Full</div></td>
                            <td><div class="col-12 badge badge-pill  badge-danger">Offline</div></td>
                          </tr>
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-lg-6 col-12 mb-4">
              <div class="card w-100">
                <div class="card-body">
                  <h2 class="card-title">Last 10 Transactions</h2>
                  <table class="table mb-0">
                    <tbody>
                      <tr>
                        <td>1</td>
                        <td>Lumini X</td>
                        <td>1/10/2018 1:45PM</td>
                        <td><div class="badge badge-pill  badge-success">Accepted</div></td>
                      </tr>
                      <tr>
                        <td>2</td>
                        <td>Primo</td>
                        <td>1/10/2018 1:49PM</td>
                        <td><div class="badge badge-pill  badge-success">Accepted</div></td>
                      </tr>
                      <tr>
                        <td>3</td>
                        <td>Lumini X</td>
                        <td>1/10/2018 1:50PM</td>
                        <td><div class="badge badge-pill badge-warning">Bill Jammed</div></td>
                      </tr>
                      <tr>
                        <td>4</td>
                        <td>WebGlow Machine</td>
                        <td>1/10/2018 2:02PM</td>
                        <td><div class="badge badge-pill  badge-success">Accepted</div></td>
                      </tr>
                      <tr>
                        <td>5</td>
                        <td>WebGlow Machine</td>
                        <td>1/10/2018 2:06PM</td>
                        <td><div class="badge badge-pill  badge-primary">Bill Rejected</div></td>
                      </tr>
                      <tr>
                        <td>6</td>
                        <td>WebGlowMachine</td>
                        <td>1/10/2018 2:35PM</td>
                        <td><div class="badge badge-pill  badge-success">Accepted</div></td>
                      </tr>
                      <tr>
                        <td>7</td>
                        <td>Lumini X</td>
                        <td>1/10/2018 2:41PM</td>
                        <td><div class="badge badge-pill  badge-success">Accepted</div></td>
                      </tr>
                      <tr>
                        <td>8</td>
                        <td>Primo</td>
                        <td>1/10/2018 2:43PM</td>
                        <td><div class="badge badge-pill  badge-danger">Cheating Detected</div></td>
                      </tr>
                      <tr>
                        <td>9</td>
                        <td>Primo</td>
                        <td>1/10/2018 2:55PM</td>
                        <td><div class="badge badge-pill  badge-success">Accepted</div></td>
                      </tr>
                      <tr>
                        <td>10</td>
                        <td>Lumini X</td>
                        <td>1/10/2018 3:46PM</td>
                        <td><div class="badge badge-pill  badge-success">Accepted</div></td>
                      </tr>
                    </tbody>
                  </table>
                  <a href="pages/tables/search.html" class="btn btn-primary">View More Transactions</a>
                </div>
              </div>
            </div>

            <div class="col-lg-6 col-12 mb-4">
                <div class="col-12 global-card">
                  <div class="card bg-primary w-100" style="background-image: url(images/vtailadvert.png);">
                    <div class="card-body text-white d-flex flex-column align-items-center justify-content-center">
                      <h2>New Mixes Available</h2>
                      <p>All new VTail Mix#25, #26 and Primo Mixes are now available, purchase now and save 10%!</p>
                      <a href="#" class="btn btn-outline-secondary">View Details</a>
                    </div>
                  </div>
                </div>
            </div>
          </div>
        </div>