      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <title>VTail Admin - Search</title>
      <!-- plugins:css -->
      <link rel="stylesheet" href="/node_modules/mdi/css/materialdesignicons.min.css">
      <link rel="stylesheet" href="/node_modules/perfect-scrollbar/dist/css/perfect-scrollbar.min.css">
      <!-- endinject -->
      <!-- plugin css for this page -->
      <link rel="stylesheet" href="/node_modules/datatables.net-bs4/css/dataTables.bootstrap4.css" />
      <link rel="stylesheet" href="/node_modules/clockpicker/dist/jquery-clockpicker.min.css" />
      <link rel="stylesheet" href="/node_modules/jquery-asColorPicker/dist/css/asColorPicker.min.css" />
      <link rel="stylesheet" href="/node_modules/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css" />
      <!-- End plugin css for this page -->
      <!-- inject:css -->
      <link rel="stylesheet" href="/css/style.css">
      <!-- endinject -->
      <link rel="shortcut icon" href="/images/favicon.png" />
